# Dockerfile used for local development, using Denon
# to restart Deno when the source code changes

FROM denoland/deno:1.15.3

WORKDIR /microservice

RUN ["deno", "install", "--allow-read", "--allow-run", "--allow-write", "--allow-net", "-f", "--unstable", "https://deno.land/x/denon@2.4.9/denon.ts"]
RUN ["chown", "-R", "deno", "/deno-dir"]

USER deno
ENTRYPOINT ["denon", "run", "--allow-env", "--allow-net", "service/server.ts"]
