version: "3"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.local
    volumes:
      - ./:/microservice
    ports:
      - 8000:8000
    env_file: .env
    depends_on:
      - db # TODO: wait for initial db bootstrap
  db:
    image: postgres:12.3
    env_file: .env
    ports:
      - 5432:5432 # TODO: hide!
    volumes:
      - ./data:/docker-entrypoint-initdb.d
