version: "3"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.local
    volumes:
      - ./:/microservice
    ports:
      - 8000:8000
    env_file: .env
    depends_on:
      - db
  db:
    image: postgres:12.3
    env_file: .env
    volumes:
      - ./data:/docker-entrypoint-initdb.d
