FROM hayd/alpine-deno:1.2.0

WORKDIR /microservice
USER deno

RUN ["deno", "install", "--allow-read", "--allow-run", "--allow-write", "--allow-net", "-f", "--unstable", "https://deno.land/x/denon@2.3.0/denon.ts"]

ENTRYPOINT ["/home/deno/.deno/bin/denon", "run", "--allow-env", "--allow-net", "service/server.ts"]
