version: "3"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.local
    volumes:
      - ./:/microservice
    ports:
      - 8000:8000
    env_file: .env
  mysql:
    image: mysql:8.0.21
    env_file: .env
    ports:
      - 3306:3306 # TODO: hide!
    volumes:
      - ./data:/docker-entrypoint-initdb.d
      - ./mysql:/etc/mysql/conf.d
